<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>Tabel 3.1 Jumlah Mahasiswa FMIPA</title>
</head>
<table cellspacing="0">
           <tr>
            <th colspan="1" align=left valign=top><font face="Times New Rowman" ></font></th>
             <th colspan="12" style="text-align: left"><font face="Times New Rowman" ><strong>Tabel 3.1</strong> Jumlah Mahasiswa FMIPA tahun akademik <?php echo Carbon::now()->startOfYear()->subYear(1)->format('Y') ?>/<?php echo Carbon::now()->startOfYear()->format('Y') ?> menurut Tipe Program dan Jenis Mahasiswa per Program Studi</font></th>
           </tr>
           <tr>
           <th></th>
           <th colspan="12" align=left valign=top style="font-size:10px" ><font face="Times New Rowman"><u>Catatan:</u></font></th>
           </tr>
           <tr>
           <th></th>
           <td colspan="12" align=left valign=top style="font-size:10px" ><font face="Times New Rowman">(1)  Mahasiswa program reguler adalah mahasiswa yang mengikuti program pendidikan secara penuh waktu (baik kelas pagi, siang, sore, malam, dan di seluruh kampus). </font></td>
           </tr>
           <tr>
           <th></th>
           <td colspan="12" align=left valign=top style="font-size:10px" ><font face="Times New Rowman">(2)  Mahasiswa program non-reguler adalah mahasiswa yang mengikuti program pendidikan secara paruh waktu.  </font></td>
           </tr>
           </tr>
           <tr>
           <th></th>
           <td colspan="12" align=left valign=top style="font-size:10px" ><font face="Times New Rowman">(3)  Mahasiswa transfer adalah mahasiswa yang masuk ke program studi dengan mentransfer mata kuliah yang telah diperolehnya dari PS lain, baik dari dalam PT maupun luar PT. </font></td>
           </tr>
           <tr>
           <th></th>
           <th colspan="12" align=left valign=top style="font-size:10px" ><font face="Times New Rowman"><u>Keterangan:</u></font></th>
           </tr>
           <tr>
           <th></th>
           <td colspan="12" align=left valign=top style="font-size:10px" ><font face="Times New Rowman"><b>G1 PS1</b>-Statistika, <b>G2 PS2</b>-Meteorologi Terapan, <b>G3 PS3</b>-Biologi, <b>G4 PS4</b>-Kimia, <b>G5 PS5</b>-Matematika, <b>G6 PS6</b>-Ilmu Komputer, <b>G7 PS7</b>-Fisika, <b>G8 PS8</b>-Biokimia, <b>G9 PS9</b>-Aktuaria</font></td>
           </tr>
            <tr>
            <th></th>
            <th rowspan="4"  style="border:1px solid #000; background-color:#daeef3;text-align: center"><font face="Times New Rowman" >Tipe</font></th>
            <th rowspan="4" style="border:1px solid #000; background-color:#daeef3;text-align: center"><font face="Times New Rowman" >Jenis Mahasiswa</font></th>
            <th rowspan="2" colspan="9" style="border:1px solid #000; background-color:#daeef3;text-align: center"><font face="Times New Rowman" >Jumlah Mahasiswa pada PS:</font></th>
            <th rowspan="2" style="border:1px solid #000; border-bottom:0px; background-color:#daeef3;text-align: center"><font face="Times New Rowman" >Total<br>Mahasiswa</font></th>
            </tr>
            <tr>
              <tr>
            <th></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS1<br> G1</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS2<br> G2</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS3<br> G3</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS4<br> G4</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS5<br> G5</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS6<br> G6</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS7<br> G7</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS8<br> G8</font></th>
            <th rowspan="2" style="border:1px solid #000; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">PS9<br> G9</font></th>
            <th rowspan="2" style="border:1px solid #000; border-top:0px; background-color:#daeef3;text-align: center" style="font-size:16px"><font face="Times New Rowman">pada<br>Fakultas</font></th>
            </tr></tr>
            <tr>
            <tr>
             <th></th>
             <td rowspan="3" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">Program reguler</font></td>
             <td rowspan="1" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">1. Mahasiswa baru bukan transfer</font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum('mbt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum('mbt_reguler') ?></font></td>
             <th rowspan="1"  align=center style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum('mbt_reguler') ?></font></th>
            </tr>
            <tr>
             <th></th>
             <td rowspan="1" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">2. Mahasiswa baru transfer</font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum('mt_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum('mt_reguler') ?></font></td>
             <th rowspan="1" align=center style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum('mt_reguler') ?></font></th>
            </tr>
            <tr>
             <th></th>
             <td rowspan="1" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">3. Total Mahasiswa reguler (Student Body)</font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum('total_reguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum('total_reguler') ?></font></td>
             <th rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum('total_reguler') ?></font></th>
            </tr>
            <tr>
             <th></th>
             <td rowspan="3" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">Program non-reguler</font></td>
             <td rowspan="1" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">1. Mahasiswa baru bukan transfer</font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" align="center" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum('mbt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum('mbt_nonreguler') ?></font></td>
             <th rowspan="1" align=center style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum('mbt_nonreguler') ?></font></th>
            </tr>
            <tr>
             <th></th>
             <td rowspan="1" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">2. Mahasiswa baru transfer</font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum('mt_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum('mt_nonreguler') ?></font></td>
             <th rowspan="1" align=center style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum('mt_nonreguler') ?></font></th>
            </tr>
            <tr>
             <th></th>
             <td rowspan="1" align=left valign=top style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman">3. Total Mahasiswa non-reguler (Student Body)</font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum('total_nonreguler') ?></font></td>
             <td rowspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum('total_nonreguler') ?></font></td>
             <th rowspan="1" align=center style="border:1px solid #000; border-width: thin; background-color:#255255255;" style="font-size:16px"><font face="Times New Rowman"><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum('total_nonreguler') ?></font></th>
            </tr>
            <tr>
            <th></th>
            <th colspan="2" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;" style="text-align: center;"><font face="Times New Rowman" >Total</font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=1)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=2)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=3)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=4)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=5)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=6)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=7)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=8)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->join('departemen', 'id_dept', '=', 'id_departemen')->where('id_departemen', $id_departemen=9)->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            <th colspan="1" align="center" style="border:1px solid #000; border-width: thin; background-color:#daeef3;"><font face="Times New Rowman" ><?php echo DB::table('jumlahs')->whereYear( 'tahun',date('Y'))->sum(DB::raw('mbt_reguler + mt_reguler + total_reguler + mbt_nonreguler + mt_nonreguler + total_nonreguler')) ?></font></th>
            </tr>
    </table>
  </body>
</html>